### ISSUE TITLE
ala-bootstrap3 and ala-admin-plugin snapshot dependencies

### ISSUE THREAD

**Issue by reupost** [AtlasOfLivingAustralia/ala-bie#22]
The dependencies for ala-bootstrap3 version '3.0.0-SNAPSHOT' and ala-admin-plugin version '2.0-SNAPSHOT' defined in build.gradle are missing.

The non -SNAPSHOT versions can be found, though.  There are a couple of other SNAPSHOT dependencies defined which are ok (bie-plugin 1.4.2-SNAPSHOT and ala-auth 3.1.0-SNAPSHOT)

**Comment by djtfmartin** [comment]
this is the same approach as in 

https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/98

**Comment by nickdos** [comment]
SNAPSHOT versions have been changed to release versions (that exist in nexus repo).
