### ISSUE TITLE
Build WAR issues

### ISSUE THREAD

**Issue by reupost** [AtlasOfLivingAustralia/ala-bie#25]
Sorry if this isn't the right place to post this.

When I build this project using either IntelliJ's 'Build artifacts' or commandline 'grails prod war', I end up with a WAR file that I can't deploy (e.g. it doesn't have a web.xml file in the WEB-INF folder). Is there something about this project that differs from the others in terms of how it should be built?

**Comment by charvolant** [comment]
I've run `./grailsw clean` followed by `./grailsw war` on the command line in the I can't see a web.xml either. However, if I then do './grailsw run-app' or deploy to tomcat, it runs happily.

So, the web.xml seems to be unnecessary. I'll investigate further.

**Comment by charvolant** [comment]
Grails 3 no longer uses web.xml

See http://docs.grails.org/latest/guide/single.html#hookingIntoRuntimeConfiguration under *Customizing the Servlet Environment*

Servlet 3.0 no longer requires a web.xml, instead configuration can be done via classes that implement the WebApplicationInitializer interface. In grails 3, this is done via spring. http://www.baeldung.com/spring-xml-vs-java-config

**Comment by reupost** [comment]
Thanks for the response, that was very helpful.  I can build and deploy locally and it does work fine (sorry, I should have tested that before posting initially). There must be something I've misconfigured on the server :/  I'm using the bie-hub.yml ansible script from ALA install, but adjusted to use the java8 and tomcat7-java8 roles, as well as my local WAR build.  I'll keep looking...

**Comment by reupost** [comment]
In case anyone else runs into this, it seems it was due to slight differences in Tomcat version between local machine and server, which was running a standalone Tomcat. It was resolved by not embedding the default Tomcat container in the WAR, i.e. changing the dependencies in build.gradle for ala-bie and bie-plugin from: 
compile "org.springframework.boot:spring-boot-starter-tomcat" 
to:
provided "org.springframework.boot:spring-boot-starter-tomcat"

**Comment by djtfmartin** [comment]
thanks @reupost

**Comment by vjrj** [comment]
More info: https://atlaslivingaustralia.slack.com/archives/CCTFGEU1G/p1572450070099100
