### ISSUE TITLE
style issue with border in tab

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/ala-bie#27]
<img width="1376" alt="screenshot 2018-07-03 16 05 33" src="https://user-images.githubusercontent.com/444897/42228109-0949ae24-7edb-11e8-87b7-af353b9662b3.png">

cc @nickdos

**Comment by djtfmartin** [comment]
https://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2902605#records

screenshot is with Chrome on a Mac

**Comment by nickdos** [comment]
@Tasilee  reported similar issue with Charts: https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:da036545-5cfd-4069-bfd3-8eb4e16f72f1#records

![image](https://user-images.githubusercontent.com/532845/47623594-97d17080-db67-11e8-956d-486328e6db72.png)


Note border above bottom charts and text all overlapping as well.
