### ISSUE TITLE
Sequences tab: show message when there are no records

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/ala-bie#44]
At present, when a taxon has no sequence records, the Sequences tab shows a "Genbank" title with no content after that.  This appears to be causing confusion (a support ticket mentions refreshing the page several times but it "not working" when a species had no sequences).

A message such as "We currently have no sequence records for (taxon name). Try (link to parent taxon sequences)", when there are no sequences for a taxon, would help.

**Comment by TaniaGLaity** [comment]
closed as sequences tab has been removed
