### ISSUE TITLE
BIE links to Lists not working

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/ala-bie#78]
Eg try a link to a list from one of the list boxes on the right hand side of this page:
https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/6485cd0c-f104-4950-8cdf-be4d09fc6bbc

The list URLs are pointing to aws-lists-prod-2022.ala.org.au instead of just lists.ala.org.au

[Museums Field Guide apps species profiles – vertebrates](https://aws-lists-prod-2022.ala.org.au/speciesListItem/list/dr1146)
[Japan-Australia Migratory Bird Agreement (JAMBA)](https://aws-lists-prod-2022.ala.org.au/speciesListItem/list/dr18988)

Raised by - @peggynewman

**Comment by sughics** [comment]
Configs updated to point to lists.ala.org.au.
