### ISSUE TITLE
BIE - ED metadata changes

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/ala-bie#79]
Example pages - https://bie-test.ala.org.au/species/https://biodiversity.org.au/afd/taxa/5c1957dc-0780-47cb-9c89-0498340c1e62

On the distribution maps in BIE, the link says stuff like:

Compiled distribution map provided by [Australia - Species of National Environmental Significance Database (Public Grids)](http://www.environment.gov.au/science/erin/databases-maps/snes)

The wording should be reframed:
link text: the `area_name` field from the [expert distribution ws](https://spatial.ala.org.au/ws/distribution/lsids/https://biodiversity.org.au/afd/taxa/5c1957dc-0780-47cb-9c89-0498340c1e62), in this case: *Expert distribution Gallinago hardwickii* 
link href: data resource page in the collectory (https://collections.ala.org.au/public/show/dr2099)
 
So it should read:
**Expert distribution Gallinago harwickii** provided by [Australia - Species of National Environmental Significance Database (Public Grids)](https://collections.ala.org.au/public/show/dr2099)

It would be great if we could work out a hack for displaying more than one ED (a 'next' link?). Some have multiple eg. Latham's Snipe https://spatial.ala.org.au/ws/distribution/lsids/https://biodiversity.org.au/afd/taxa/5c1957dc-0780-47cb-9c89-0498340c1e62 
Presently BIE seems to choose at random which is sub optimal.

Raised by: @peggynewman

**Comment by sat01a** [comment]
Feature request - Added to the backlog

**Comment by adam-collins** [comment]
Any suggestions to make these buttons look nicer?



![Image](https://github.com/AtlasOfLivingAustralia/ala-bie/assets/8031500/a456d117-8378-41c5-92be-0c4e5c3c5924)

**Comment by adam-collins** [comment]
Use image carousel instead of buttons as shown

**Comment by adam-collins** [comment]
![Image](https://github.com/AtlasOfLivingAustralia/ala-bie/assets/8031500/33d111bc-4c00-497b-b1c1-c7decbdd0fab)

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ala-bie-hub/pull/39
